//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ImTryin.T4.Roslyn.csproj documents:
//   D:\Projects\ImTryin\ImTryin.T4\ImTryin.T4.Roslyn\obj\Debug\netstandard2.0\ImTryin.T4.Roslyn.AssemblyInfo.cs
using Microsoft.EntityFrameworkCore;

namespace ImTryin.T4.Roslyn.EfTest
{
    public partial class Author
    {
    }
}
namespace ImTryin.T4.Roslyn.EfTest
{
    public partial class BaseEntity
    {
    }
}
namespace ImTryin.T4.Roslyn.EfTest
{
    public partial class Book
    {
         public long? AuthorId { get; set; }
    }
}

namespace ImTryin.T4.Roslyn.EfTest
{
    public partial class TestDbContext
    {
        public DbSet<ImTryin.T4.Roslyn.EfTest.Author> Authors { get; set; }
        public DbSet<ImTryin.T4.Roslyn.EfTest.Book> Books { get; set; }
    }
}
